remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: 8th Workshop on Advanced Analytics and Learning on Temporal Data
description: AALTD is a candidate workshop for ECML 2023
