remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "8th Workshop on Advanced Analytics and Learning on Temporal Data (AALTD 2023)"
description: "AALTD has been accepted as a satellite workshop for ECML / PKDD 2023"
